name: Deploy Content to sentinel-ws [0fd25282-f201-4a8c-bef6-0c1f16d0395d]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-0fd25282-f201-4a8c-bef6-0c1f16d0395d.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ master ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-0fd25282-f201-4a8c-bef6-0c1f16d0395d.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'sentinel'
      workspaceName: 'sentinel-ws'
      workspaceId: '45bfba10-52fa-4586-966c-e055fd6af080'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule'
      branch: 'master'
      sourceControlId: '0fd25282-f201-4a8c-bef6-0c1f16d0395d'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_0fd25282f2014a8cbef60c1f16d0395d }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_0fd25282f2014a8cbef60c1f16d0395d }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_0fd25282f2014a8cbef60c1f16d0395d }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_0fd25282f2014a8cbef60c1f16d0395d }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_0fd25282f2014a8cbef60c1f16d0395d }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_0fd25282f2014a8cbef60c1f16d0395d }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_0fd25282f2014a8cbef60c1f16d0395d }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_0fd25282f2014a8cbef60c1f16d0395d }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_0fd25282f2014a8cbef60c1f16d0395d }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-0fd25282-f201-4a8c-bef6-0c1f16d0395d.ps1